[2021-09-28 10:40:33 +0000] [669] [INFO] Starting gunicorn 20.0.4
[2021-09-28 10:40:33 +0000] [669] [INFO] Listening at: http://0.0.0.0:8000 (669)
[2021-09-28 10:40:33 +0000] [669] [INFO] Using worker: threads
[2021-09-28 10:40:33 +0000] [672] [INFO] Booting worker with pid: 672
Mysql closed the connection. Perform reconnect...
Connection was already closed.
/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py:162: RuntimeWarning: Got OperationalError: (2003, "Can't connect to MySQL server on 'crm.123medhk.com' ([Errno 111] Connection refused)"). Please, check that you have migrated the database via python manage.py migrate
  self._real_add_job(job, jobstore_alias, replace_existing)
Exception during getting jobs
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'crm.123medhk.com' ([Errno 111] Connection refused)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django_apscheduler/jobstores.py", line 68, in get_due_jobs
    out = self._get_jobs(next_run_time__lte=serialize_dt(now))
  File "/usr/local/lib/python3.6/site-packages/django_apscheduler/jobstores.py", line 153, in _get_jobs
    for job_id, job_state in job_states:
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 144, in __iter__
    return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1052, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'crm.123medhk.com' ([Errno 111] Connection refused)")
Exception during get_next_run_time for jobs
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'crm.123medhk.com' ([Errno 111] Connection refused)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django_apscheduler/jobstores.py", line 78, in get_next_run_time
    return deserialize_dt(DjangoJob.objects.filter(next_run_time__isnull=False).earliest('next_run_time').next_run_time)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 646, in earliest
    return self._earliest(*fields, field_name=field_name)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 643, in _earliest
    return obj.get()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'crm.123medhk.com' ([Errno 111] Connection refused)")
Internal Server Error: /admin/Record/everytask/11218/change/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 189, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'crm.123medhk.com' ([Errno 111] Connection refused)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 212, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 186, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 256, in inner
    self._setup()
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 392, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 182, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 54, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 194, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'crm.123medhk.com' ([Errno 111] Connection refused)")
Internal Server Error: /admin/Record/everytask/11219/change/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 189, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'crm.123medhk.com' ([Errno 111] Connection refused)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 212, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 186, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 256, in inner
    self._setup()
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 392, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 182, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 54, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 194, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'crm.123medhk.com' ([Errno 111] Connection refused)")
[2021-09-28 11:08:39 +0000] [669] [INFO] Handling signal: term
[2021-09-28 19:08:39 +0800] [672] [INFO] Worker exiting (pid: 672)
[2021-09-28 11:08:39 +0000] [669] [INFO] Shutting down: Master
[2021-09-28 11:08:54 +0000] [668] [INFO] Starting gunicorn 20.0.4
[2021-09-28 11:08:54 +0000] [668] [INFO] Listening at: http://0.0.0.0:8000 (668)
[2021-09-28 11:08:54 +0000] [668] [INFO] Using worker: threads
[2021-09-28 11:08:54 +0000] [671] [INFO] Booting worker with pid: 671
[2021-09-28 11:19:51 +0000] [668] [INFO] Handling signal: term
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-09-26 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-09-29 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-09-28 19:10:19.145432) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-09-28 19:10:20.446927) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-09-27 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-09-28 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-09-28 19:15:18.752745) while time zone support is active.
  RuntimeWarning)
[2021-09-28 19:19:51 +0800] [671] [INFO] Worker exiting (pid: 671)
[2021-09-28 11:19:51 +0000] [668] [INFO] Shutting down: Master
[2021-09-28 11:20:03 +0000] [667] [INFO] Starting gunicorn 20.0.4
[2021-09-28 11:20:03 +0000] [667] [INFO] Listening at: http://0.0.0.0:8000 (667)
[2021-09-28 11:20:03 +0000] [667] [INFO] Using worker: threads
[2021-09-28 11:20:03 +0000] [670] [INFO] Booting worker with pid: 670
Internal Server Error: /admin/Record/everytask/11219/change/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 189, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'crm.123medhk.com' ([Errno 111] Connection refused)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 212, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 186, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 256, in inner
    self._setup()
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 392, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 182, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 54, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 194, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'crm.123medhk.com' ([Errno 111] Connection refused)")
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-09-26 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-09-29 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-09-28 19:25:07.994315) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-09-27 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-09-28 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-09-28 20:20:08.390432) while time zone support is active.
  RuntimeWarning)
Not Found: /.env
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /robots.txt
Not Found: /sitemap.xml
Not Found: /.well-known/security.txt
Not Found: /text4041632841619
Not Found: /HNAP1
Not Found: /sdk
Not Found: /evox/about
Not Found: /boaform/admin/formLogin
Not Found: /HNAP1/
Not Found: /robots.txt
Not Found: /.env
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /config/getuser
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /solr/admin/info/system
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
Not Found: /api/jsonws/invoke
Not Found: /index.php
Not Found: /console/
Not Found: /Autodiscover/Autodiscover.xml
Not Found: /_ignition/execute-solution
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /boaform/admin/formLogin
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
Not Found: /setup.cgi
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-09-27 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-09-30 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-09-29 00:00:00) while time zone support is active.
  RuntimeWarning)
Not Found: /boaform/admin/formLogin
Not Found: /boaform/admin/formLogin
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /config/getuser
Not Found: /wp-includes/js/jquery/jquery.js
Not Found: /administrator/help/en-GB/toc.json
Not Found: /administrator/language/en-GB/install.xml
Not Found: /plugins/system/debug/debug.xml
Not Found: /administrator/
Not Found: /misc/ajax.js
Not Found: /admin/view/javascript/common.js
Not Found: /admin/includes/general.js
Not Found: /images/editor/separator.gif
Not Found: /js/header-rollup-554.js
Not Found: /vendor/phpunit/phpunit/build.xml
Not Found: /fckeditor/editor/filemanager/connectors/php/upload.php
Not Found: /.env
Not Found: /wp-admin/setup-config.php
Not Found: /wordpress/wp-admin/setup-config.php
Not Found: /wp/wp-admin/setup-config.php
Not Found: /blog/wp-admin/setup-config.php
Not Found: /test/wp-admin/setup-config.php
Not Found: /site/wp-admin/setup-config.php
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /boaform/admin/formLogin
Not Found: /sql/webdb/index.php
Not Found: /database/index.php
Not Found: /phpmyadmin2020/index.php
Not Found: /sql/sql/index.php
Not Found: /administrator/db/index.php
Not Found: /PMA2014/index.php
Not Found: /phpmyadmin2018/index.php
Not Found: /phpmyAdmin/index.php
Not Found: /pma2021/index.php
Not Found: /db/index.php
Not Found: /db/websql/index.php
Not Found: /db/webadmin/index.php
Not Found: /PMA2014/index.php
Not Found: /sql/phpmanager/index.php
Not Found: /pma2020/index.php
Not Found: /mysql/pma/index.php
Not Found: /phpMyAdmin-5.1.1/index.php
Not Found: /phpMyAdmin-5.1.1/index.php
Not Found: /.env
Forbidden (CSRF cookie not set.): /
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /boaform/admin/formLogin
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-09-29 19:00:08.207620) while time zone support is active.
  RuntimeWarning)
Internal Server Error: /login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/root/SMSTask/Twilio/Appis/User/views.py", line 51, in post
    request.session['layout'] = settings.FUNC_LAYOUT
AttributeError: module 'Twilio.settings' has no attribute 'FUNC_LAYOUT'
Internal Server Error: /login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/root/SMSTask/Twilio/Appis/User/views.py", line 51, in post
    request.session['layout'] = settings.FUNC_LAYOUT
AttributeError: module 'Twilio.settings' has no attribute 'FUNC_LAYOUT'
Internal Server Error: /login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/root/SMSTask/Twilio/Appis/User/views.py", line 51, in post
    request.session['layout'] = settings.FUNC_LAYOUT
AttributeError: module 'Twilio.settings' has no attribute 'FUNC_LAYOUT'
Internal Server Error: /login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/root/SMSTask/Twilio/Appis/User/views.py", line 51, in post
    request.session['layout'] = settings.FUNC_LAYOUT
AttributeError: module 'Twilio.settings' has no attribute 'FUNC_LAYOUT'
[2021-09-29 11:36:22 +0000] [667] [INFO] Handling signal: term
[2021-09-29 19:36:22 +0800] [670] [INFO] Worker exiting (pid: 670)
[2021-09-29 11:36:23 +0000] [667] [INFO] Shutting down: Master
[2021-09-29 11:36:35 +0000] [668] [INFO] Starting gunicorn 20.0.4
[2021-09-29 11:36:35 +0000] [668] [INFO] Listening at: http://0.0.0.0:8000 (668)
[2021-09-29 11:36:35 +0000] [668] [INFO] Using worker: threads
[2021-09-29 11:36:35 +0000] [671] [INFO] Booting worker with pid: 671
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-09-27 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-09-30 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-09-28 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-09-29 00:00:00) while time zone support is active.
  RuntimeWarning)
Not Found: /contact/undefined
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /api/jsonws/invoke
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /solr/admin/info/system
Not Found: /index.php
Not Found: /console/
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
Not Found: /Autodiscover/Autodiscover.xml
Not Found: /_ignition/execute-solution
Not Found: /boaform/admin/formLogin
Not Found: /aaa9
Not Found: /aab9
Not Found: /boaform/admin/formLogin
Not Found: /phpMyAdmin3/index.php
Not Found: /phpMyAdmin3/index.php
Not Found: /robots.txt
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
Not Found: /administrator/db/index.php
Not Found: /phpMyAdmin5/index.php
Not Found: /phpMyAdmin5/index.php
Not Found: /boaform/admin/formLogin
Not Found: /boaform/admin/formLogin
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-09-28 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-01 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-09-30 10:01:44.873395) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-09-30 00:00:00) while time zone support is active.
  RuntimeWarning)
Not Found: /ReportServer
Not Found: /portal/redlion
Not Found: /hudson
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /boaform/admin/formLogin
Not Found: /robots.txt
Not Found: /sitemap.xml
Not Found: /.well-known/security.txt
Not Found: /config/getuser
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /config/getuser
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /api/jsonws/invoke
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /Autodiscover/Autodiscover.xml
Not Found: /_ignition/execute-solution
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
Not Found: /solr/admin/info/system
Not Found: /index.php
Not Found: /console/
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /boaform/admin/formLogin
Not Found: /boaform/admin/formLogin
Not Found: /.git/config
Not Found: /setup.cgi
Not Found: /boaform/admin/formLogin
Not Found: /shell
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /system_api.php
Not Found: /c/version.js
Not Found: /streaming/clients_live.php
Not Found: /stalker_portal/c/version.js
Not Found: /stream/live.php
Not Found: /flu/403.html
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /.env
Forbidden (CSRF cookie not set.): /
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-09-29 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-02 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-10-01 00:00:00) while time zone support is active.
  RuntimeWarning)
Not Found: /config/getuser
Not Found: /db/db-admin/index.php
Not Found: /db/db-admin/index.php
Not Found: /PMA2018/index.php
Not Found: /admin/index.php
Not Found: /PMA2014/index.php
Not Found: /phpmyadmin2/index.php
Not Found: /mysql/pma/index.php
Not Found: /phpmyadmin2019/index.php
Not Found: /pma2014/index.php
Not Found: /mysql/pma/index.php
Not Found: /sql/phpmanager/index.php
Not Found: /sql/sql-admin/index.php
Not Found: /sql/phpmyadmin3/index.php
Not Found: /phpMyAdmin5/index.php
Not Found: /phpMyAdmin5/index.php
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /boaform/admin/formLogin
Not Found: /boaform/admin/formLogin
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /solr/admin/info/system
Not Found: /index.php
Not Found: /api/jsonws/invoke
Not Found: /Autodiscover/Autodiscover.xml
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
Not Found: /console/
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /_ignition/execute-solution
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /pma/index.php
Not Found: /admin/index.php
Not Found: /phpmyadmin2/index.php
Not Found: /pma2019/index.php
Not Found: /phpMyAdmin-5.1.1-english/index.php
Not Found: /phpMyAdmin-5.1.1-english/index.php
Not Found: /boaform/admin/formLogin
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /config/getuser
Not Found: /config/getuser
Not Found: /phpmyadmin/
Not Found: /phpmyadmin/
Not Found: /config/getuser
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /config/getuser
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /config/getuser
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-03 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-10-02 00:00:00) while time zone support is active.
  RuntimeWarning)
Not Found: /config/getuser
Not Found: /manager/html
Not Found: /_ignition/execute-solution
Not Found: /api/jsonws/invoke
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /console/
Not Found: /Autodiscover/Autodiscover.xml
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
Not Found: /solr/admin/info/system
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /index.php
Not Found: /boaform/admin/formLogin
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
mysqldump: [Warning] Using a password on the command line interface can be insecure.
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-02 16:12:03) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-02 16:12:04.957301) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-12-01 16:12:04) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2022-03-31 16:12:04) while time zone support is active.
  RuntimeWarning)
Not Found: /config/getuser
Not Found: /.env
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-02 17:03:30) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-02 17:03:32.200971) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-12-01 17:03:32) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2022-03-31 17:03:32) while time zone support is active.
  RuntimeWarning)
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /config/getuser
Not Found: /stalker_portal/server/tools/auth_simple.php
Not Found: /boaform/admin/formLogin
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /login.action
Not Found: /robots.txt
Not Found: /sitemap.xml
Not Found: /robots.txt
Not Found: /sitemap.xml
Not Found: /.well-known/security.txt
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /w00tw00t.at.blackhats.romanian.anti-sec:)
Not Found: /phpMyAdmin/scripts/setup.php
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /boaform/admin/formLogin
Not Found: /robots.txt
Not Found: /h5/
Forbidden (CSRF token missing or incorrect.): /
Forbidden (CSRF token missing or incorrect.): /
Not Found: /homes/
Not Found: /kefu.php
Not Found: /homes/
Not Found: /api/apps
Not Found: /config.js
Not Found: /getLocale
Not Found: /user/Login
Not Found: /js/home.js
Not Found: /style.css
Not Found: /common.js
Not Found: /api/linkPF
Not Found: /Css/Hm.css
Not Found: /admin/index
Not Found: /css/app.css
Not Found: /m/allticker/1
Not Found: /fePublicInfo/
Not Found: /nyyh/game.css
Not Found: /langConfig.js
Not Found: /css/style.css
Not Found: /im/in/GetUuid
Not Found: /im/App/config
Not Found: /img/close.png
Not Found: /api/contactWay
Not Found: /proxy/settings
Not Found: /app/js/base.js
Not Found: /m/ticker/usdtqc
Not Found: /anquan/qgga.asp
Not Found: /home/main/login
Not Found: /api/index/index
Not Found: /user/allroleinfo
Not Found: /banner.do
Not Found: /verification.asp
Not Found: /index/api/config
Not Found: /script/public.js
Not Found: /Home/Bind/binding
Not Found: /appxz/index.html
Not Found: /Home/Index/ajaxTJ
Not Found: /csjs/bankCheck.js
Not Found: /css/nsc/reset.css
Not Found: /Home/Get/getJnd28
Not Found: /skin/js/common.js
Not Found: /JS/loginstatus.js
Not Found: /legal/currency/set
Not Found: /Pc/Lang/index.html
Not Found: /views/home/home.js
Not Found: /api/v1/member/kefu
Not Found: /manager/js/left.js
Not Found: /public/img/cz1.png
Not Found: /wap/banner/details
Not Found: /login/kefuxian.mvc
Not Found: /files/pub_reset.css
Not Found: /room/script/face.js
Not Found: /assets/js/dmshub.js
Not Found: /Public/js/common.js
Not Found: /api/index/webconfig
Not Found: /room/getRoomBangFans
Not Found: /Promotions/list.mvc
Not Found: /index/login/register
Not Found: /api/Index/getLottery
Not Found: /api/v1/borrowxx.html
Not Found: /api/common/getConfig
Not Found: /Content/Wap/base.css
Not Found: /api/user/mobilelogin
Not Found: /api/index/grailindex
Not Found: /data/json/config.json
Not Found: /jiaoyimao/default.css
Not Found: /cscpLoginWeb/app/home
Not Found: /Public/Home/js/cls.js
Not Found: /lanren/css/global.css
Not Found: /css/view/main/goin.css
Not Found: /Public/Home/js/game.js
Not Found: /xianyu/index/setp1.html
Not Found: /Public/css/errorCss.css
Not Found: /css/view/main/style.css
Not Found: /ajax
Not Found: /zz2/address.php
Not Found: /member/js/lang_zh_CN.js
Not Found: /api/customerServiceLink
Not Found: /Public/Home/js/common.js
Not Found: /guess/list.php
Not Found: /client/api/findFreeTrade
Not Found: /assets/app-manifest.json
Not Found: /s_api/basic/download/info
Not Found: /Public/home/js/fukuang.js
Not Found: /Content/css/wzwstylel.css
Not Found: /app/common/getRegisterSet
Not Found: /Public/Wchat/css/index.css
Not Found: /template/920ka/css/lsy.css
Not Found: /template/tmp1/js/common.js
Not Found: /public/h5static/js/main.js
Not Found: /api/currency/quotation_new
Not Found: /Public/mobile/js/config.js
Not Found: /Template/Mobile/js/main.js
Not Found: /index.php/Wap/Api/getBanner
Not Found: /market/market-ws/iframe.html
Not Found: /config.php
Not Found: /api/system/system/config/get
Not Found: /Public/uploads/web/step1.png
Not Found: /mobile/v3/appSuperDownload.do
Not Found: /api/web/user/getIndexData.php
Not Found: /public/web/css/add//index.css
Not Found: /melody/api/v1/pageconfig/list
Not Found: /getConfig/getArticle.do
Not Found: /cscpLoginWeb/scripts/public.js
Not Found: /Public/home/common/js/index.js
Not Found: /public/appapi/images/error.jpg
Not Found: /index.php/api/other/appSetting
Not Found: /assets/room/css/room_mobile.css
Not Found: /api/mobile/checkStrategyHistory
Not Found: /infe/rest/flash/getServerIP.json
Not Found: /index/Mobile/fenshi
Not Found: /Public/Home/images/game/pk10.png
Not Found: /wap/trading/get_newallorder_ajax
Not Found: /api/public/
Not Found: /base/exchange_index/changepwdfirst
Not Found: /assets/extension/market/css/mt4.css
Not Found: /assets/dist/static/js/vendor_prod.js
Not Found: /public/admin.php/api/index/loansList
Not Found: /Templates/user/finance/css/userPay.css
Not Found: /api/stock/getSingleStock.do
Not Found: /index.php
Not Found: /public/static/home/js/moblie/login.js
Not Found: /base/exchange_article/index/classid/1/id/1
Not Found: /Public/Home/ecshe_css/main.css
Not Found: /common/template/lottery/lecai/css/style.css
Not Found: /Public/Mobile/ecshe_css/wapmain.css
Not Found: /infe/rest/fig/advertise/common.json
Not Found: /client/api/findConfigByKey
Not Found: /api/v/index/queryOfficePage
Not Found: /ipl/app/flash/publicbmw/ball/FigLeaf.js
Not Found: /json/configs/permanent/permanent-lottery-config-list.json
Not Found: /getConfig/listPopFrame.do
Not Found: /api/product/topRank
Not Found: /api/v1/about
Not Found: /api/config-init
Not Found: /public/static/css/denglu.css
Not Found: /auth/oauth/token
Not Found: /api/jsonws/invoke
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /index.php
Not Found: /console/
Not Found: /solr/admin/info/system
Not Found: /_ignition/execute-solution
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
Not Found: /Autodiscover/Autodiscover.xml
Not Found: /config/getuser
Not Found: /c/
Not Found: /404/index.html
Not Found: /404/index.html
Not Found: /config/getuser
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /core/.env
Forbidden (CSRF cookie not set.): /
Not Found: /app/.env
Forbidden (CSRF cookie not set.): /
Not Found: /public/.env
Forbidden (CSRF cookie not set.): /
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-04 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-10-03 00:00:00) while time zone support is active.
  RuntimeWarning)
Not Found: /portal/redlion
Not Found: /fuN3
Not Found: /config/getuser
Not Found: /config/getuser
Not Found: /hudson
Not Found: /config/getuser
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /config/getuser
Not Found: /.env
Forbidden (CSRF cookie not set.): /
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /boaform/admin/formLogin
Not Found: /boaform/admin/formLogin
Not Found: /boaform/admin/formLogin
Not Found: /shell
Not Found: /_ignition/execute-solution
Not Found: /console/
Not Found: /index.php
Not Found: /solr/admin/info/system
Not Found: /api/jsonws/invoke
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /Autodiscover/Autodiscover.xml
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /config/getuser
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /manager/text/list
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /manager/html
Not Found: /boaform/admin/formLogin
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /config/getuser
Not Found: /config/getuser
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-05 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-10-04 00:00:00) while time zone support is active.
  RuntimeWarning)
Not Found: /Portal/Portal.mwsl
Not Found: /xY7T
Not Found: /nmaplowercheck1633317710
Not Found: /owa/auth/x.js
Not Found: /.git/HEAD
Not Found: /sdk
Not Found: /nmaplowercheck1633317715
Not Found: /CSS/Miniweb.css
Not Found: /main.cfm
Not Found: /scripts/WPnBr.dll
Not Found: /Portal0000.htm
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /boaform/admin/formLogin
Not Found: /api/jsonws/invoke
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /solr/admin/info/system
Not Found: /index.php
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
Not Found: /console/
Not Found: /Autodiscover/Autodiscover.xml
Not Found: /_ignition/execute-solution
Not Found: /boaform/admin/formLogin
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /.env
Not Found: /shell
Not Found: /boaform/admin/formLogin
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /boaform/admin/formLogin
Not Found: /lixuan.php
Not Found: /lixuan.php
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-06 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-10-05 00:00:00) while time zone support is active.
  RuntimeWarning)
Not Found: /Telerik.Web.UI.WebResource.axd
Not Found: /.env
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /api/jsonws/invoke
Not Found: /solr/admin/info/system
Not Found: /index.php
Not Found: /console/
Not Found: /_ignition/execute-solution
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /Autodiscover/Autodiscover.xml
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
Not Found: /boaform/admin/formLogin
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /setup.cgi
Not Found: /config/getuser
Not Found: /setup.cgi
Not Found: /boaform/admin/formLogin
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
Not Found: /shell
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /api/jsonws/invoke
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /solr/admin/info/system
Not Found: /index.php
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
Not Found: /console/
Not Found: /Autodiscover/Autodiscover.xml
Not Found: /_ignition/execute-solution
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /images/logo-tiny.png
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-07 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-10-06 00:00:00) while time zone support is active.
  RuntimeWarning)
Not Found: /portal/redlion
Not Found: /actuator/health
Not Found: /hudson
Not Found: /boaform/admin/formLogin
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /setup.cgi
Not Found: /boaform/admin/formLogin
Not Found: /shell
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-06 15:44:03) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-06 15:44:04.309938) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-12-05 15:44:04) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2022-04-04 15:44:04) while time zone support is active.
  RuntimeWarning)
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /.DS_Store
Not Found: /server-status
Not Found: /config.json
Not Found: /GponForm/diag_Form
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /boaform/admin/formLogin
Not Found: /boaform/admin/formLogin
Not Found: /.env
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /config/getuser
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /fuN3
Not Found: /boaform/admin/formLogin
Not Found: /phpmyadmin/index.php
Not Found: /config/getuser
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /api/jsonws/invoke
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /solr/admin/info/system
Not Found: /index.php
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
Not Found: /console/
Not Found: /Autodiscover/Autodiscover.xml
Not Found: /_ignition/execute-solution
Not Found: /solr/
Not Found: /wp-includes/wlwmanifest.xml
Not Found: /xmlrpc.php
Not Found: /blog/wp-includes/wlwmanifest.xml
Not Found: /web/wp-includes/wlwmanifest.xml
Not Found: /wordpress/wp-includes/wlwmanifest.xml
Not Found: /website/wp-includes/wlwmanifest.xml
Not Found: /wp/wp-includes/wlwmanifest.xml
Not Found: /news/wp-includes/wlwmanifest.xml
Not Found: /2018/wp-includes/wlwmanifest.xml
Not Found: /2019/wp-includes/wlwmanifest.xml
Not Found: /shop/wp-includes/wlwmanifest.xml
Not Found: /wp1/wp-includes/wlwmanifest.xml
Not Found: /test/wp-includes/wlwmanifest.xml
Not Found: /media/wp-includes/wlwmanifest.xml
Not Found: /wp2/wp-includes/wlwmanifest.xml
Not Found: /site/wp-includes/wlwmanifest.xml
Not Found: /cms/wp-includes/wlwmanifest.xml
Not Found: /sito/wp-includes/wlwmanifest.xml
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /boaform/admin/formLogin
Not Found: /.env
Forbidden (CSRF cookie not set.): /
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-08 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-10-07 00:00:00) while time zone support is active.
  RuntimeWarning)
Not Found: /config/getuser
Not Found: /ReportServer
Not Found: /phpmyadmin/
Not Found: /.env
[2021-10-07 10:14:21 +0000] [667] [INFO] Starting gunicorn 20.0.4
[2021-10-07 10:14:21 +0000] [667] [INFO] Listening at: http://0.0.0.0:8000 (667)
[2021-10-07 10:14:21 +0000] [667] [INFO] Using worker: threads
[2021-10-07 10:14:21 +0000] [670] [INFO] Booting worker with pid: 670
Not Found: /contact/undefined
Not Found: /task/undefined
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-07 18:20:03) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-07 18:20:05.379367) while time zone support is active.
  RuntimeWarning)
Internal Server Error: /api/area/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 189, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 410, in initial
    self.perform_authentication(request)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/usr/local/lib/python3.6/site-packages/rest_framework/request.py", line 220, in user
    self._authenticate()
  File "/usr/local/lib/python3.6/site-packages/rest_framework/request.py", line 373, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/authentication.py", line 123, in authenticate
    if not user or not user.is_active:
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 256, in inner
    self._setup()
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 392, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 182, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 54, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 194, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
django.db.utils.OperationalError: (2013, 'Lost connection to MySQL server during query')
[2021-10-07 10:49:20 +0000] [667] [INFO] Handling signal: term
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-07 18:25:18.302997) while time zone support is active.
  RuntimeWarning)
[2021-10-07 18:49:21 +0800] [670] [INFO] Worker exiting (pid: 670)
[2021-10-07 10:49:21 +0000] [667] [INFO] Shutting down: Master
[2021-10-07 10:49:31 +0000] [669] [INFO] Starting gunicorn 20.0.4
[2021-10-07 10:49:31 +0000] [669] [INFO] Listening at: http://0.0.0.0:8000 (669)
[2021-10-07 10:49:31 +0000] [669] [INFO] Using worker: threads
[2021-10-07 10:49:31 +0000] [672] [INFO] Booting worker with pid: 672
Not Found: /TP/public/index.php
[2021-10-07 11:14:08 +0000] [669] [INFO] Handling signal: term
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-07 18:56:02.025052) while time zone support is active.
  RuntimeWarning)
[2021-10-07 19:14:09 +0800] [672] [INFO] Worker exiting (pid: 672)
[2021-10-07 11:14:09 +0000] [669] [INFO] Shutting down: Master
[2021-10-07 12:04:31 +0000] [668] [INFO] Starting gunicorn 20.0.4
[2021-10-07 12:04:31 +0000] [668] [INFO] Listening at: http://0.0.0.0:8000 (668)
[2021-10-07 12:04:31 +0000] [668] [INFO] Using worker: threads
[2021-10-07 12:04:31 +0000] [671] [INFO] Booting worker with pid: 671
[2021-10-07 12:07:40 +0000] [668] [INFO] Handling signal: term
[2021-10-07 20:07:41 +0800] [671] [INFO] Worker exiting (pid: 671)
[2021-10-07 12:07:41 +0000] [668] [INFO] Shutting down: Master
[2021-10-07 12:33:52 +0000] [671] [INFO] Starting gunicorn 20.0.4
[2021-10-07 12:33:52 +0000] [671] [INFO] Listening at: http://0.0.0.0:8000 (671)
[2021-10-07 12:33:52 +0000] [671] [INFO] Using worker: threads
[2021-10-07 12:33:52 +0000] [674] [INFO] Booting worker with pid: 674
[2021-10-07 12:38:05 +0000] [671] [INFO] Handling signal: term
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-05 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-08 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-10-06 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-10-07 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-07 20:36:30.664228) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-07 20:37:02.096925) while time zone support is active.
  RuntimeWarning)
[2021-10-07 20:38:06 +0800] [674] [INFO] Worker exiting (pid: 674)
[2021-10-07 12:38:06 +0000] [671] [INFO] Shutting down: Master
[2021-10-07 12:38:17 +0000] [668] [INFO] Starting gunicorn 20.0.4
[2021-10-07 12:38:17 +0000] [668] [INFO] Listening at: http://0.0.0.0:8000 (668)
[2021-10-07 12:38:17 +0000] [668] [INFO] Using worker: threads
[2021-10-07 12:38:17 +0000] [671] [INFO] Booting worker with pid: 671
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-05 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-08 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-10-06 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-10-07 00:00:00) while time zone support is active.
  RuntimeWarning)
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /nmaplowercheck1633628590
Not Found: /.git/HEAD
Not Found: /Th0p
Not Found: /sdk
Not Found: /scripts/WPnBr.dll
Not Found: /HNAP1
Not Found: /docs/cplugError.html/
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /api/jsonws/invoke
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /index.php
Not Found: /solr/admin/info/system
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
Not Found: /console/
Not Found: /Autodiscover/Autodiscover.xml
Not Found: /_ignition/execute-solution
Not Found: /config/getuser
Not Found: /config/getuser
Not Found: /robots.txt
Not Found: /config/getuser
Not Found: /sql/sql-admin/index.php
Not Found: /phpmyadmin2/index.php
Not Found: /phpmyadmin2016/index.php
Not Found: /PMA2018/index.php
Not Found: /administrator/db/index.php
Not Found: /pma2020/index.php
Not Found: /phpmyadmin2021/index.php
Not Found: /admin/db/index.php
Not Found: /phpMyAdmin1/index.php
Not Found: /phpMyAdmin1/index.php
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-06 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-09 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-08 10:00:33.421468) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-10-08 00:00:00) while time zone support is active.
  RuntimeWarning)
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /robots.txt
Not Found: /sitemap.xml
Not Found: /.well-known/security.txt
Not Found: /config.json
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /boaform/admin/formLogin
Not Found: /robots.txt
Not Found: /contact/undefined
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /contact/undefined
Not Found: /contact/undefined
Not Found: /contact/undefined
Not Found: /contact/undefined
Not Found: /contact/undefined
Not Found: /contact/undefined
Not Found: /boaform/admin/formLogin
Not Found: /robots.txt
Not Found: /boaform/admin/formLogin
Not Found: /boaform/admin/formLogin
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /config/getuser
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-08 20:00:32.231967) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-08 20:01:33.347758) while time zone support is active.
  RuntimeWarning)
Not Found: /shell
Not Found: /boaform/admin/formLogin
Not Found: /mysql/admin/index.php
Not Found: /mysql/pma/index.php
Not Found: /phpmyadmin2016/index.php
Not Found: /php-myadmin/index.php
Not Found: /phpMyAdmin4/index.php
Not Found: /phpMyAdmin4/index.php
Not Found: /test_404_page/
Not Found: /issmall/
Not Found: /administrator/manifests/files/joomla.xml
Not Found: /docs.css
Not Found: /phpmyadmin/themes/original/img/logo_right.png
Not Found: /phpmyadmin/favicon.ico
Not Found: /phpmyadmin/docs.css
Not Found: /fckeditor/fckconfig.js
Not Found: /fckeditor/editor/dtd/fck_dtd_test.html
Not Found: /fckeditor/license.txt
Not Found: /fckeditor/editor/js/fckeditorcode_ie.js
Not Found: /fckeditor/fckeditor.js
Not Found: /FCK/editor/js/fckeditorcode_ie.js
Not Found: /FCK/fckeditor.js
Not Found: /fckeditor.js
Not Found: /editor/fckeditor.js
Not Found: /editor/js/fckeditorcode_ie.js
Not Found: /tpl/user/tpl1/css/skins/blue.css
Not Found: /images/login/eyoumail.gif
Not Found: /images/login/logo.gif
Not Found: /tpl/login/user/images/login_bg_1.jpg
Not Found: /images/login/icon-up.gif
Not Found: /docs/
Not Found: /ckeditor/ckeditor.js
Not Found: /config/getuser
Not Found: /new_gb/help/images/usage/3.3.gif
Not Found: /web2/login_template/1.files/Logo1.jpg
Not Found: /License.txt
Not Found: /e/master/login.aspx
Not Found: /master/login.aspx
Not Found: /ckfinder/ckfinder.html
Not Found: /ckfinder/install.txt
Not Found: /ckeditor/ckfinder/ckfinder.html
Not Found: /ckeditor/ckfinder/install.txt
Not Found: /auth/login
Not Found: /list.php
Not Found: /admin/template/article_more/config.htm
Not Found: /inc/rsd.php
Not Found: /rss.php
Not Found: /Images/login/biaoti.jpg
Not Found: /Images/login/lefttu.jpg
Not Found: /Images/login/mainlogo.gif
Not Found: /next/img/logo.gif
Not Found: /maintlogin.jsp
Not Found: /common/help/images/helplogo.gif
Not Found: /common/help/images/helplogo_zh.gif
Not Found: /coremail/common/help/images/helplogo_zh.gif
Not Found: /coremail/common/help/images/helplogo.gif
Not Found: /archiver
Not Found: /tools/rss.aspx
Not Found: /admin/inc/xml.xslt
Not Found: /Ntalker/lawfirm.aspx
Not Found: /Search.html
Not Found: /siteserver/upgrade/default.aspx
Not Found: /siteserver/login.aspx
Not Found: /UserCenter/css/admin/bgimg/admin_all_bg.png
Not Found: /dialog/dialog.js
Not Found: /Editor.js
Not Found: /images/2_11.gif
Not Found: /js/buttons.js
Not Found: /index.php
Not Found: /index.php
Not Found: /index.php
Not Found: /index.php
Not Found: /help/ch_gb/images/help-title.gif
Not Found: /admin/index.php
Not Found: /bencandy.php
Not Found: /images/default/post_bt.gif
Not Found: /CuteSoft_Client/CuteEditor/ImageEditor/listfiles.aspx
Not Found: /CuteSoft_Client/CuteEditor/Help/default.htm
Not Found: /CuteSoft_Client/CuteEditor/Images/log.gif
Not Found: /CuteSoft_Client/CuteEditor/Style/IE.css
Not Found: /index.cgi
Not Found: /cgi/index.cgi
Not Found: /default/images/logo.gif
Not Found: /extman/default/images/logo.gif
Not Found: /archive/archive.css
Not Found: /clientscript/vbulletin_ajax_htmlloader.js
Not Found: /admin/js/IdSUtil.js
Not Found: /ids/admin/login.jsp
Not Found: /ids/admin/userhome/forgetPwd.jsp
Not Found: /feed.asp
Not Found: /images/hwem.css
Not Found: /app/home/skins/default/style.css
Not Found: /extern.php
Not Found: /addons/theme/stv1/_static/image/favicon.ico
Not Found: /apps/admin/_static/image/login_box_bg.png
Not Found: /addons/theme/stv1/_static/ts2/layout.css
Not Found: /addons/theme/stv2/_static/ts2/layout.css
Not Found: /404.jpg
Not Found: /images/login9/login_33.jpg
Not Found: /admin/SouthidcEditor/Dialog/dialog.js
Not Found: /admin/SouthidcEditor/ewebeditor.asp
Not Found: /admin/SouthidcEditor/ButtonImage/standard/componentmenu.gif
Not Found: /app/login.jsp
Not Found: /app/js/source/wcmlib/WCMConstants.js
Not Found: /console/js/CWCMDialogHead.js
Not Found: /console/include/not_login.htm
Not Found: /console/auth/reg_newuser.jsp
Not Found: /console/js/CTRSRequestParam.js
Not Found: /app/images/login/logo.png
Not Found: /app/images/login/toplogo.gif
Not Found: /default/css/em_css.css
Not Found: /history.txt
Not Found: /common/common.js
Not Found: /inc/Templates/rss.xslt
Not Found: /advfile/ad12.js
Not Found: /helpnew/faq/faq_simple_zh_CN.jsp
Not Found: /ymail/images/index_r1_c4.jpg
Not Found: /skin/frontend/default/modern/css/styles.css
Not Found: /admin.php
Not Found: /README.txt
Not Found: /pub/guiedit/guiedit.js
Not Found: /pub/skins/pmwiki/pmwiki.css
Not Found: /docs/DOCUMENTATION.txt
Not Found: /template/1/bluewise/_files/jspxcms.css
Not Found: /back/scripts/jspxcms_choose.js
Not Found: /Wq_StranJF.js
Not Found: /admin/login.asp
Not Found: /install
Not Found: /plugin.php
Not Found: /admin/login.aspx
Not Found: /Error.aspx
Not Found: /inc/playerKinds.xml
Not Found: /app/Tpl/fanwe_1/js/DD_belatedPNG_0.0.8a-min.js
Not Found: /User/Login.aspx
Not Found: /API/DW/Dwplugin/TemplateManage/manage_site.htm
Not Found: /API/DW/Dwplugin/TemplateManage/save_template.htm
Not Found: /API/DW/Dwplugin/ThirdPartyTags/SiteFactory.xml
Not Found: /Admin/Common/HelpLinks.xml
Not Found: /API/DW/Dwplugin/TemplateManage/login_site.htm
Not Found: /API/DW/Dwplugin/SystemLabel/SiteConfig.htm
Not Found: /Admin/Login.aspx
Not Found: /Admin/Images/LoginImages/admin_text.gif
Not Found: /Template/Default/Skin/user/images/login_back.jpg
Not Found: /Prompt/images/P_Wrong.gif
Not Found: /Admin/Images/LoginImages/admin_top.gif
Not Found: /deptWebsiteAction.do
Not Found: /admin/start/index.php
Not Found: /Scripts/jquery/maticsoft.jquery.min.js
Not Found: /script/valid_formdata.js
Not Found: /media/com_hikashop/js/hikashop.js
Not Found: /templates/jsn_glass_pro/ext/hikashop/jsn_ext_hikashop.css
Not Found: /kindeditor-min.js
Not Found: /kindeditor.js
Not Found: /lang/en.js
Not Found: /themes/default/default.css
Not Found: /examples/index.html
Not Found: /examples/file-manager.html
Not Found: /plugins/filemanager/filemanager/js
Not Found: /plugins/anchor/anchor.js
Not Found: /asp.net/README.txt
Not Found: /examples/readonly.html
Not Found: /help/user/index.html
Not Found: /index.php
Not Found: /robots.txt
Not Found: /public/js/ipb.js
Not Found: /whir_system/login.aspx
Not Found: /whir_system/module/security/login.aspx
Not Found: /system/Login.aspx
Not Found: /themes/graphics/horde-power1.png
Not Found: /themes/default/graphics/favicon.ico
Not Found: /themes/default/graphics/horde-power1.png
Not Found: /style/default/hdwiki.css
Not Found: /doku.php
Not Found: /rss.aspx
Not Found: /max-templates/classic/styles/app.css
Not Found: /images/logo_product-cml.png
Not Found: /forums/list.page
Not Found: /admin/login.php
Not Found: /images/logo_88x31.gif
Not Found: /licence.txt
Not Found: /stylesheet.css
Not Found: /includes/general.js
Not Found: /include/dedeajax2.js
Not Found: /data/admin/ver.txt
Not Found: /include/dialog/config.php
Not Found: /plus/download.php
Not Found: /digg.php
Not Found: /plus/sitemap.html
Not Found: /plus/rssmap.html
Not Found: /plus/heightsearch.php
Not Found: /member/space/company/info.txt
Not Found: /forum.php
Not Found: /archiver/
Not Found: /uc_server/control/admin/db.php
Not Found: /CHANGELOG.txt
Not Found: /changelog.txt
Not Found: /Help
Not Found: /images/branding/logo.gif
Not Found: /Install/logo.gif
Not Found: /adminsoft/templates/images/login_bg_top.jpg
Not Found: /Include/EcsServerApi.js
Not Found: /jcms/index.jsp
Not Found: /jcms/index_jcms.jsp
Not Found: /ks_inc/ajax.js
Not Found: /api/api_user.xml
Not Found: /m
Not Found: /base/login/login.php
Not Found: /template/home.htm
Not Found: /system/skins/default/system.login.htm
Not Found: /system/language/zh-cn.xml
Not Found: /js/ajax_x.js
Not Found: /ycportal/js/wbTextBox/showimg.jsp
Not Found: /images/login_Name.jpg
Not Found: /admin.php
Not Found: /plug/publish
Not Found: /login/Jeecms.do
Not Found: /datacenter/downloadApp/showDownload.do
Not Found: /webbuilder/script/locale/wb-lang-zh_CN.js
Not Found: /imagesschool/style1/flash2.jpg
Not Found: /Public/Admin/Images/login_main_bg.jpg
Not Found: /admin/admin_login.php
Not Found: /data/images/wap_logo.gif
Not Found: /nobody/mobile.htm
Not Found: /script/login.js
Not Found: /Site/Pages/WebResources.ashx/PoweredByKodakImage
Not Found: /Site/SystemThemes/7917A0869761B5458281E407AE0090F5/Images/ISBanner58px.jpg
Not Found: /public/about.html
Not Found: /help/en/h_authenticate.html
Not Found: /system/Update.aspx
Not Found: /customdir/images/english_logo.jpg
Not Found: /images/favicon.ico
Not Found: /images/logo-white.png
Not Found: /images/zh-CN/logo.ico
Not Found: /wp-cron.php
Not Found: /wp-content
Not Found: /wp-login.php
Not Found: /license.txt
Not Found: /readme.html
Not Found: /img/pic/login/top-left.jpg
Not Found: /business/images/index-gg1.jpg
Not Found: /images/Default_bg_002.gif
Not Found: /eams/static/scripts/grade/course/input.js
Not Found: /custom/SkinTemplate/skin/public/images/sys-logo-1caitong-180.jpg
Not Found: /include/install_ocx.aspx
Not Found: /was/help.jsp
Not Found: /was5/web/index.jsp
Not Found: /was/main.html
Not Found: /logo/logo_jw.png
Not Found: /task/administrator/manifests/files/joomla.xml
Not Found: /task/docs.css
Not Found: /task/phpmyadmin/themes/original/img/logo_right.png
Not Found: /task/phpmyadmin/favicon.ico
Not Found: /task/phpmyadmin/docs.css
Not Found: /task/docs/
Not Found: /task/ckeditor/ckeditor.js
Not Found: /task/tpl/user/tpl1/css/skins/blue.css
Not Found: /task/favicon.ico
Not Found: /task/images/login/eyoumail.gif
Not Found: /task/images/login/logo.gif
Not Found: /task/tpl/login/user/images/login_bg_1.jpg
Not Found: /task/images/login/icon-up.gif
Not Found: /task/fckeditor/fckconfig.js
Not Found: /task/fckeditor/editor/dtd/fck_dtd_test.html
Not Found: /task/fckeditor/license.txt
Not Found: /task/fckeditor/editor/js/fckeditorcode_ie.js
Not Found: /task/fckeditor/fckeditor.js
Not Found: /task/FCK/editor/js/fckeditorcode_ie.js
Not Found: /task/FCK/fckeditor.js
Not Found: /task/fckeditor.js
Not Found: /task/editor/fckeditor.js
Not Found: /task/editor/js/fckeditorcode_ie.js
Not Found: /task/new_gb/help/images/usage/3.3.gif
Not Found: /task/web2/login_template/1.files/Logo1.jpg
Not Found: /task/License.txt
Not Found: /task/ckfinder/ckfinder.html
Not Found: /task/ckfinder/install.txt
Not Found: /task/ckeditor/ckfinder/ckfinder.html
Not Found: /task/ckeditor/ckfinder/install.txt
Not Found: /task/auth/login
Not Found: /task/common/help/images/helplogo.gif
Not Found: /task/common/help/images/helplogo_zh.gif
Not Found: /task/admin
Not Found: /task/list.php
Not Found: /task/admin/template/article_more/config.htm
Not Found: /task/Images/login/biaoti.jpg
Not Found: /task/Images/login/lefttu.jpg
Not Found: /task/Images/login/mainlogo.gif
Not Found: /task/next/img/logo.gif
Not Found: /task/maintlogin.jsp
Not Found: /task/admin/inc/xml.xslt
Not Found: /siteserver/login.aspx
Not Found: /task/dialog/dialog.js
Not Found: /task/Editor.js
Not Found: /task/images/2_11.gif
Not Found: /task/js/buttons.js
Not Found: /task/bencandy.php
Not Found: /task/images/default/post_bt.gif
Not Found: /task/help/ch_gb/images/help-title.gif
Not Found: /task/admin/index.php
Not Found: /task/CuteSoft_Client/CuteEditor/ImageEditor/listfiles.aspx
Not Found: /task/CuteSoft_Client/CuteEditor/Help/default.htm
Not Found: /task/CuteSoft_Client/CuteEditor/Images/log.gif
Not Found: /task/CuteSoft_Client/CuteEditor/Style/IE.css
Not Found: /task/index.cgi
Not Found: /task/cgi/index.cgi
Not Found: /task/default/images/logo.gif
Not Found: /task/index.php
Not Found: /task/index.php
Not Found: /task/index.php
Not Found: /task/index.php
Not Found: /task/images/hwem.css
Not Found: /task/addons/theme/stv1/_static/image/favicon.ico
Not Found: /task/apps/admin/_static/image/login_box_bg.png
Not Found: /task/addons/theme/stv1/_static/ts2/layout.css
Not Found: /task/addons/theme/stv2/_static/ts2/layout.css
Not Found: /task/images/login9/login_33.jpg
Not Found: /task/admin/SouthidcEditor/Dialog/dialog.js
Not Found: /task/admin/SouthidcEditor/ewebeditor.asp
Not Found: /task/admin/SouthidcEditor/ButtonImage/standard/componentmenu.gif
Not Found: /task/app/login.jsp
Not Found: /task/app/js/source/wcmlib/WCMConstants.js
Not Found: /task/console/js/CWCMDialogHead.js
Not Found: /task/console/include/not_login.htm
Not Found: /task/console/auth/reg_newuser.jsp
Not Found: /task/console/js/CTRSRequestParam.js
Not Found: /task/app/images/login/logo.png
Not Found: /task/app/images/login/toplogo.gif
Not Found: /task/default/css/em_css.css
Not Found: /task/advfile/ad12.js
Not Found: /task/helpnew/faq/faq_simple_zh_CN.jsp
Not Found: /task/ymail/images/index_r1_c4.jpg
Not Found: /task/skin/frontend/default/modern/css/styles.css
Not Found: /task/README.txt
Not Found: /task/pub/guiedit/guiedit.js
Not Found: /task/pub/skins/pmwiki/pmwiki.css
Not Found: /task/docs/DOCUMENTATION.txt
Not Found: /task/template/1/bluewise/_files/jspxcms.css
Not Found: /task/back/scripts/jspxcms_choose.js
Not Found: /task/Wq_StranJF.js
Not Found: /task/admin/login.asp
Not Found: /task/install
Not Found: /task/admin/login.aspx
Not Found: /task/Error.aspx
Not Found: /task/inc/playerKinds.xml
Not Found: /task/app/Tpl/fanwe_1/js/DD_belatedPNG_0.0.8a-min.js
Not Found: /task/User/Login.aspx
Not Found: /task/API/DW/Dwplugin/TemplateManage/manage_site.htm
Not Found: /task/API/DW/Dwplugin/TemplateManage/save_template.htm
Not Found: /task/API/DW/Dwplugin/ThirdPartyTags/SiteFactory.xml
Not Found: /task/Admin/Common/HelpLinks.xml
Not Found: /task/API/DW/Dwplugin/TemplateManage/login_site.htm
Not Found: /task/API/DW/Dwplugin/SystemLabel/SiteConfig.htm
Not Found: /task/Admin/Login.aspx
Not Found: /task/Admin/Images/LoginImages/admin_text.gif
Not Found: /task/Template/Default/Skin/user/images/login_back.jpg
Not Found: /task/Prompt/images/P_Wrong.gif
Not Found: /task/Admin/Images/LoginImages/admin_top.gif
Not Found: /task/deptWebsiteAction.do
Not Found: /task/admin/start/index.php
Not Found: /task/Scripts/jquery/maticsoft.jquery.min.js
Not Found: /task/script/valid_formdata.js
Not Found: /task/media/com_hikashop/js/hikashop.js
Not Found: /task/templates/jsn_glass_pro/ext/hikashop/jsn_ext_hikashop.css
Not Found: /task/kindeditor-min.js
Not Found: /task/kindeditor.js
Not Found: /task/lang/en.js
Not Found: /task/themes/default/default.css
Not Found: /task/examples/index.html
Not Found: /task/examples/file-manager.html
Not Found: /task/plugins/filemanager/filemanager/js
Not Found: /task/plugins/anchor/anchor.js
Not Found: /task/asp.net/README.txt
Not Found: /task/examples/readonly.html
Not Found: /task/doku.php
Not Found: /task/whir_system/login.aspx
Not Found: /task/whir_system/module/security/login.aspx
Not Found: /task/system/Login.aspx
Not Found: /task/public/js/ipb.js
Not Found: /task/style/default/hdwiki.css
Not Found: /task/forums/list.page
Not Found: /task/stylesheet.css
Not Found: /task/includes/general.js
Not Found: /task/archiver
Not Found: /task/tools/rss.aspx
Not Found: /task/inc/rsd.php
Not Found: /task/rss.php
Not Found: /task/feed.asp
Not Found: /task/archive/archive.css
Not Found: /task/clientscript/vbulletin_ajax_htmlloader.js
Not Found: /task/adminsoft/templates/images/login_bg_top.jpg
Not Found: /task/Ntalker/lawfirm.aspx
Not Found: /task/Search.html
Not Found: /task/inc/Templates/rss.xslt
Not Found: /task/jcms/index.jsp
Not Found: /task/jcms/index_jcms.jsp
Not Found: /task/extern.php
Not Found: /task/404.jpg
Not Found: /task/history.txt
Not Found: /task/common/common.js
Not Found: /task/ks_inc/ajax.js
Not Found: /task/api/api_user.xml
Not Found: /task/js/ajax_x.js
Not Found: /task/template/home.htm
Not Found: /task/system/skins/default/system.login.htm
Not Found: /task/system/language/zh-cn.xml
Not Found: /task/static/hgicon.png
Not Found: /task/index.php
Not Found: /task/robots.txt
Not Found: /task/rss.aspx
Not Found: /task/max-templates/classic/styles/app.css
Not Found: /task/admin.php
Not Found: /task/licence.txt
Not Found: /task/admin/
Not Found: /task/admin/login.php
Not Found: /task/images/logo_88x31.gif
Not Found: /task/Public/Admin/Images/login_main_bg.jpg
Not Found: /task/public/about.html
Not Found: /task/help/en/h_authenticate.html
Not Found: /task/customdir/images/english_logo.jpg
Not Found: /task/images/zh-CN/logo.ico
Not Found: /task/images/favicon.ico
Not Found: /task/images/logo-white.png
Not Found: /task/include/dedeajax2.js
Not Found: /task/data/admin/ver.txt
Not Found: /task/include/dialog/config.php
Not Found: /task/plus/download.php
Not Found: /task/digg.php
Not Found: /task/plus/sitemap.html
Not Found: /task/plus/rssmap.html
Not Found: /task/plus/heightsearch.php
Not Found: /task/member/space/company/info.txt
Not Found: /task/CHANGELOG.txt
Not Found: /task/changelog.txt
Not Found: /task/images/branding/logo.gif
Not Found: /task/Install/logo.gif
Not Found: /task/m
Not Found: /task/ycportal/js/wbTextBox/showimg.jsp
Not Found: /task/login/Jeecms.do
Not Found: /task/webbuilder/script/locale/wb-lang-zh_CN.js
Not Found: /task/Site/Pages/WebResources.ashx/PoweredByKodakImage
Not Found: /task/Site/SystemThemes/7917A0869761B5458281E407AE0090F5/Images/ISBanner58px.jpg
Not Found: /task/nobody/mobile.htm
Not Found: /task/forum.php
Not Found: /task/archiver/
Not Found: /task/uc_server/control/admin/db.php
Not Found: /task/img/pic/login/top-left.jpg
Not Found: /task/images/Default_bg_002.gif
Not Found: /task/custom/SkinTemplate/skin/public/images/sys-logo-1caitong-180.jpg
Not Found: /task/static/images/logo/webserver_small.gif
Not Found: /task/admin/admin_login.php
Not Found: /task/data/images/wap_logo.gif
Not Found: /task/wp-cron.php
Not Found: /task/wp-content
Not Found: /task/wp-login.php
Not Found: /task/license.txt
Not Found: /task/readme.html
Not Found: /task/logo/logo_jw.png
Not Found: /task/was/help.jsp
Not Found: /task/was5/web/index.jsp
Not Found: /task/was/main.html
Not Found: /task/phpmyadmin/
Not Found: /task/weblog/
Not Found: /task/blog/
Not Found: /task/forum/
Not Found: /task/bbs/
Not Found: /task/wcm/
Not Found: /task/admin/editor/
Not Found: /wp-content/
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /shell
Not Found: /config/getuser
Not Found: /shell
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-07 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-10 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-10-09 00:00:00) while time zone support is active.
  RuntimeWarning)
Not Found: /portal/redlion
Not Found: /actuator/health
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /api/jsonws/invoke
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /index.php
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
Not Found: /console/
Not Found: /_ignition/execute-solution
Not Found: /solr/admin/info/system
Not Found: /Autodiscover/Autodiscover.xml
Not Found: /hudson
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /boaform/admin/formLogin
Not Found: /HNAP1/
Not Found: /config/getuser
Not Found: /webfig/
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /contact/undefined
[2021-10-09 10:55:27 +0000] [668] [INFO] Handling signal: term
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-09 17:57:32) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-09 17:57:33.432385) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-09 17:57:33) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-09 17:57:34.580831) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-09 17:57:34) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-09 17:57:36.118712) while time zone support is active.
  RuntimeWarning)
[2021-10-09 18:55:28 +0800] [671] [INFO] Worker exiting (pid: 671)
[2021-10-09 10:55:28 +0000] [668] [INFO] Shutting down: Master
[2021-10-09 10:55:40 +0000] [669] [INFO] Starting gunicorn 20.0.4
[2021-10-09 10:55:40 +0000] [669] [INFO] Listening at: http://0.0.0.0:8000 (669)
[2021-10-09 10:55:40 +0000] [669] [INFO] Using worker: threads
[2021-10-09 10:55:40 +0000] [672] [INFO] Booting worker with pid: 672
Not Found: /contact/undefined
Not Found: /task/undefined
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-09 18:57:03) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-09 18:57:05.144104) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-11-08 18:57:05) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-09 18:57:05) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-09 18:57:06.628588) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-11-08 18:57:06) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-07 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-10 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-10-08 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-10-09 00:00:00) while time zone support is active.
  RuntimeWarning)
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /404/index.html
Not Found: /404/index.html
Not Found: /boaform/admin/formLogin
Not Found: /.env
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /pma2012/index.php
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /boaform/admin/formLogin
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
Not Found: /nmaplowercheck1633813192
Not Found: /HNAP1
Not Found: /evox/about
Not Found: /sdk
Not Found: /robots.txt
Not Found: /boaform/admin/formLogin
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /boaform/admin/formLogin
Not Found: /api/jsonws/invoke
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /solr/admin/info/system
Not Found: /index.php
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
Not Found: /console/
Not Found: /Autodiscover/Autodiscover.xml
Not Found: /_ignition/execute-solution
Not Found: /config/getuser
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-08 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EveryTask.send_finish_time received a naive datetime (2021-10-11 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField EmailApply.next_time received a naive datetime (2021-10-10 00:00:00) while time zone support is active.
  RuntimeWarning)
Not Found: /mysql/web/index.php
Not Found: /phpMyAdmin2/index.php
Not Found: /phpMyAdmin2/index.php
Not Found: /config/getuser
Not Found: /fuN3
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Not Found: /boaform/admin/formLogin
Not Found: /HNAP1/
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /shell
Not Found: /config/getuser
Not Found: /boaform/admin/formLogin
Not Found: /config/getuser
Not Found: /config/getuser
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /api/jsonws/invoke
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /solr/admin/info/system
Not Found: /index.php
Not Found: /wp-content/plugins/wp-file-manager/readme.txt
Not Found: /console/
Not Found: /Autodiscover/Autodiscover.xml
Not Found: /_ignition/execute-solution
Not Found: /boaform/admin/formLogin
Not Found: /manager/text/list
Not Found: /config/getuser
Not Found: /.env
Forbidden (CSRF cookie not set.): /
Not Found: /setup.cgi
Not Found: /boaform/admin/formLogin
Not Found: /boaform/admin/formLogin
Not Found: /manager/html
Not Found: /.env
Forbidden (CSRF cookie not set.): /
